#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for AI Orchestrator Security Audit
# Spec: 003-corrections

set -e

echo "========================================"
echo "AI Orchestrator v5.2 - Security Audit Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL AUDIT TOOLS
# ============================================

echo ""
echo -e "${YELLOW}Installing audit tools...${NC}"

pip install --quiet ruff pylint vulture pip-audit pytest-cov

echo -e "${GREEN}Audit tools installed:${NC}"
echo "  - ruff $(ruff --version 2>&1 | head -1)"
echo "  - pylint $(pylint --version 2>&1 | head -1)"
echo "  - vulture $(vulture --version 2>&1 | head -1)"
echo "  - pip-audit $(pip-audit --version 2>&1 | head -1)"

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo ""
echo -e "${YELLOW}Verifying project structure...${NC}"

if [ ! -f "backend/main.py" ]; then
    echo -e "${RED}ERROR: backend/main.py not found${NC}"
    exit 1
fi

if [ ! -f "backend/auth.py" ]; then
    echo -e "${RED}ERROR: backend/auth.py not found${NC}"
    exit 1
fi

if [ ! -f "backend/security.py" ]; then
    echo -e "${RED}ERROR: backend/security.py not found${NC}"
    exit 1
fi

if [ ! -f "backend/requirements.txt" ]; then
    echo -e "${RED}ERROR: backend/requirements.txt not found${NC}"
    exit 1
fi

echo -e "${GREEN}All key files present${NC}"

# ============================================
# RUN QUICK BASELINE CHECKS
# ============================================

echo ""
echo -e "${YELLOW}Running baseline checks...${NC}"

# Check for datetime.utcnow() usage
echo -n "  datetime.utcnow() occurrences: "
grep -c 'datetime.utcnow()' backend/auth.py 2>/dev/null || echo "0"

# Check for python-jose
echo -n "  python-jose in requirements: "
if grep -q 'python-jose' backend/requirements.txt; then
    echo -e "${RED}YES (deprecated)${NC}"
else
    echo -e "${GREEN}NO (clean)${NC}"
fi

# Check pyproject.toml for S rules
echo -n "  Security rules in pyproject.toml: "
if grep -qE 'select.*S' backend/pyproject.toml; then
    echo -e "${GREEN}YES${NC}"
else
    echo -e "${YELLOW}NO (needs adding)${NC}"
fi

# ============================================
# START SERVICES (if Docker available)
# ============================================

if command -v docker &> /dev/null; then
    echo ""
    echo -e "${YELLOW}Docker detected. Starting services...${NC}"

    # Build and start backend
    docker compose build backend --quiet 2>/dev/null || echo -e "${YELLOW}Docker build skipped${NC}"
    docker compose up -d backend 2>/dev/null || echo -e "${YELLOW}Docker start skipped${NC}"

    # Wait for health
    sleep 5
    if curl -s http://localhost:8001/health > /dev/null 2>&1; then
        echo -e "${GREEN}Backend healthy on port 8001${NC}"
    else
        echo -e "${YELLOW}Backend not responding (may need manual start)${NC}"
    fi
else
    echo ""
    echo -e "${YELLOW}Docker not available. Manual service start required.${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Security Audit!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8001"
echo "  Health Check: http://localhost:8001/health"
echo ""
echo "Audit Commands:"
echo "  ruff check --select=E,F,I,S,B,C4,UP backend/"
echo "  pylint --fail-under=9.0 backend/*.py"
echo "  pip-audit -r backend/requirements.txt"
echo "  vulture backend/ --min-confidence 100"
echo ""
echo "Next Step: Run the coder agent to begin Phase 1 (Audit)"
echo ""
